In [1]:
import numpy as np
import pandas as pd

We will study the eigenvalue distribution of random symmetric matrices using NumPy. Our objective in this notebook will be to generate data that will be analyzed in a separate notebook. 

NumPy will be used to compute the data, which will be stored in a Pandas database. We will then save the data in a CSV file.

## Demonstration

In [2]:
n=5
M=np.random.randn(n,n)
print(M)

[[ 0.32206073 -0.17598479  0.71907044 -0.65395021  1.69109124]
 [ 1.175519   -0.68170401 -0.46051095  0.37821436  0.11357754]
 [-2.28617961 -0.88111796  0.3333679   0.25374682  1.0093433 ]
 [ 0.16080155  0.67469406 -0.12280111 -2.00555538  0.13864873]
 [-0.56273159 -0.57073639 -0.76282456  0.21701331 -0.82693156]]


In [3]:
M=(M+M.T)/2
print(M)

[[ 0.32206073  0.49976711 -0.78355458 -0.24657433  0.56417983]
 [ 0.49976711 -0.68170401 -0.67081445  0.52645421 -0.22857943]
 [-0.78355458 -0.67081445  0.3333679   0.06547286  0.12325937]
 [-0.24657433  0.52645421  0.06547286 -2.00555538  0.17783102]
 [ 0.56417983 -0.22857943  0.12325937  0.17783102 -0.82693156]]


In [4]:
w=np.linalg.eigvalsh(M) #Hermetian eigenvalues
print(w)

[-2.34037873 -1.13147308 -0.81199364 -0.02905094  1.45413405]


## Data generation

Use a Python dictionary to store our results. 

Each of the elements of the dictionary must be a list of the same length.

In [5]:
df={'n':[],
    'sample':[],
    'eigenvalues':[]
   }
nsample=40
for n in [5,10,20,40,100]:
  for sample in range(nsample):
    M=np.random.randn(n,n)
    M=M+M.T
    w=np.linalg.eigvalsh(M)
    df['n']+=[n]*n # this makes a list n long 
    df['sample']+=[sample]*n
    df['eigenvalues']+=list(w)
  

In [6]:
df=pd.DataFrame(df)
df.to_csv("random_matrix.csv",index=False)
print(df)

      eigenvalues    n  sample
0       -5.309022    5       0
1       -2.873055    5       0
2       -1.162407    5       0
3        0.692094    5       0
4        4.574199    5       0
5       -6.336344    5       1
6       -0.489910    5       1
7        0.210429    5       1
8        1.540272    5       1
9        4.598000    5       1
10      -5.107202    5       2
11      -2.210910    5       2
12      -1.044847    5       2
13       3.003807    5       2
14       5.029341    5       2
15      -4.737656    5       3
16      -0.208702    5       3
17       0.762118    5       3
18       3.508637    5       3
19       6.340800    5       3
20      -5.805864    5       4
21      -4.373316    5       4
22      -0.789561    5       4
23       1.605939    5       4
24       3.788008    5       4
25      -5.021339    5       5
26      -0.771096    5       5
27       0.451586    5       5
28       1.841965    5       5
29       4.635712    5       5
...           ...  ...     ...
6970    